# perf script event handlers, generated by perf script -g python
# Licensed under the terms of the GNU GPL License version 2

# The common_* event handler fields are the most useful fields common to
# all events.  They don't necessarily correspond to the 'common_*' fields
# in the format files.  Those fields not available as handler params can
# be retrieved using Python functions of the form common_*(context).
# See the perf-trace-python Documentation for the list of available functions.

import os
import sys

sys.path.append(os.environ['PERF_EXEC_PATH'] + \
  '/scripts/python/Perf-Trace-Util/lib/Perf/Trace')

from perf_trace_context import *
from Core import *
from Util import *

syscalls = autodict()

def trace_begin():
  pass

def trace_end():
  pass

def raw_syscalls__sys_exit(event_name, context, cpu,
    s, ns, pid, comm, callchain, syscall_id, args):
  if pid not in syscalls or syscall_id not in syscalls[pid]:
    return
  latency = nsecs(s, ns) - syscalls[pid][syscall_id]
  print "[%04d] %04d => %9uns" % (pid, syscall_id, latency)

def raw_syscalls__sys_enter(event_name, context, cpu,
    s, ns, pid, comm, callchain, syscall_id, ret):
  syscalls[pid][syscall_id] = nsecs(s, ns)

def trace_unhandled(event_name, context, event_fields_dict):
  pass

