apiVersion: v1
kind: ServiceAccount
metadata:
  name: exos
  namespace: default

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exocompute
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exocompute
subjects:
  - kind: ServiceAccount
    name: exos
    namespace: default
roleRef:
  kind: ClusterRole
  name: exocompute
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  name: exec-execlib
  labels:
    app: exec-execlib
spec:
  serviceAccountName: exos
  restartPolicy: Never
  containers:
  - name: exec-execlib
    image: gcr.io/spark-dev-004/exec-execlib
