copy1:
	cp ~/Projects/usernet/mutated/iatimes.csv iatimes_exp.csv
	cp ~/Projects/usernet/ghola/iatimes.csv iatimes_emp.csv

copy2:
	cp ~/Projects/usernet/smutated/iatimes.csv_0 iatimes_exp.csv
	cp ~/Projects/usernet/ghola/iatimes.csv iatimes_emp.csv

test:
	./fileio.py iatimes_exp.csv iatimes_emp.csv

